//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Payments')
export class PaymentsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  paymentMethods: string;

  @Column('text', { nullable: true })
  defaultPaymentMethod: string;

  @Column('text', { nullable: true })
  paymentHistory: string;

  @Column('integer', { nullable: true })
  driverPayout: number;
}
