//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Vehicles')
export class VehiclesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  vehicleInformation: string;

  @Column('text', { nullable: true })
  vehicleDetails: string;

  @Column('text', { nullable: true })
  photos: string;

  @Column('text', { nullable: true })
  verificationDocuments: string;

  @Column('text', { nullable: true })
  availability: string;
}
