//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const DriversTitle = () => {
  const record = useRecordContext();
  return <span>Drivers {record ? `"${record.id}"` : ''}</span>;
};

export const DriversList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <ReferenceField source="profileInformation" reference="users" />
      <TextField source="accountSettings" />
      <ReferenceField source="vehicles" reference="Vehicles" />
      <ReferenceField source="bookings" reference="Rides" />
      <TextField source="tripHistory" />
      <NumberField source="earnings" />
      <TextField source="navigation" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const DriversEdit = () => (
  <Edit title={<DriversTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <ReferenceInput source="profileInformation" reference="users" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="accountSettings" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="vehicles" reference="Vehicles" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="bookings" reference="Rides" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="tripHistory" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="earnings" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="navigation" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const DriversCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <ReferenceInput source="profileInformation" reference="users" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="accountSettings" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="vehicles" reference="Vehicles" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="bookings" reference="Rides" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="tripHistory" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="earnings" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="navigation" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  <ReferenceInput
    source="profileInformation"
    label="profileInformation"
    reference="users"
    alwaysOn
  />,
  ,
  <ReferenceInput
    source="vehicles"
    label="vehicles"
    reference="Vehicles"
    alwaysOn
  />,
  <ReferenceInput
    source="bookings"
    label="bookings"
    reference="Rides"
    alwaysOn
  />,
  ,
  ,
  ,
];
