//Source code generated by AppGPT (www.appgpt.tech)
import { Admin, Resource, CustomRoutes } from 'react-admin';
import { customDataProvider } from './dataProvider';
import fakeDataProvider from 'ra-data-fakerest';
import { Dashboard } from './dashboard';
import { authProvider, apInitialize } from './authProvider';
import { i18nProvider } from './i18nProvider';
import LoginPage, { Login } from './Login';
import data from './data';
import { UsersList, UsersCreate, UsersEdit } from './resources/Users';
import { DriversList, DriversCreate, DriversEdit } from './resources/Drivers';
import { RidesList, RidesCreate, RidesEdit } from './resources/Rides';
import {
  VehiclesList,
  VehiclesCreate,
  VehiclesEdit,
} from './resources/Vehicles';
import {
  PaymentsList,
  PaymentsCreate,
  PaymentsEdit,
} from './resources/Payments';
import UsersIcon from '@mui/icons-material/Person';
import DriversIcon from '@mui/icons-material/DriveEta';
import RidesIcon from '@mui/icons-material/DirectionsCar';
import VehiclesIcon from '@mui/icons-material/DirectionsCar';
import PaymentsIcon from '@mui/icons-material/Payment';
// SUPERTOKENS
import React from 'react';
import SuperTokens, {
  SuperTokensWrapper,
  getSuperTokensRoutesForReactRouterDom,
} from 'supertokens-auth-react';
import ThirdPartyPasswordless from 'supertokens-auth-react/recipe/thirdpartypasswordless';
import Session from 'supertokens-auth-react/recipe/session';
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';
import * as reactRouterDom from 'react-router-dom';
let sessionFn = Session.init();
SuperTokens.init({
  appInfo: {
    appName: import.meta.env.VITE_SUPERTOKENS_APPNAME,
    apiDomain: import.meta.env.VITE_BACKEND_DOMAIN,
    websiteDomain: import.meta.env.VITE_SUPERTOKENS_WEBSITEDOMAIN,
    apiBasePath: import.meta.env.VITE_BACKEND_APIPATH + '/auth',
    websiteBasePath: import.meta.env.VITE_SUPERTOKENS_WEBSITEBASEPATH,
  },
  recipeList: [
    ThirdPartyPasswordless.init({
      contactMethod: 'EMAIL',
      signInUpFeature: {
        providers: [
          ThirdPartyPasswordless.Github.init(),
          //ThirdPartyPasswordless.Google.init(),
          //ThirdPartyPasswordless.Facebook.init(),
          //ThirdPartyPasswordless.Apple.init(),
        ],
      },
    }),
    sessionFn,
  ],
});
apInitialize(Session);
// END SUPERTOKENS
let dataProvider: any;
if (import.meta.env.VITE_USE_BACKEND_DATA === 'true') {
  dataProvider = customDataProvider(
    import.meta.env.VITE_BACKEND_DOMAIN +
      import.meta.env.VITE_BACKEND_APIPATH +
      '/proxy',
  );
} else {
  dataProvider = fakeDataProvider(data.defaultData);
}

const App = () => (
  <SuperTokensWrapper>
    <BrowserRouter basename="/ac02faddd">
      <Admin
        authProvider={
          import.meta.env.VITE_ENVIRONMENT != 'DEV' ? authProvider : undefined
        }
        requireAuth
        loginPage={LoginPage}
        dataProvider={dataProvider}
        i18nProvider={i18nProvider}
        dashboard={Dashboard}
      >
        <Resource
          name="Users"
          options={{ label: 'Users' }}
          list={UsersList}
          create={UsersCreate}
          edit={UsersEdit}
          recordRepresentation="name"
          icon={UsersIcon}
        />
        <Resource
          name="Drivers"
          options={{ label: 'Drivers' }}
          list={DriversList}
          create={DriversCreate}
          edit={DriversEdit}
          recordRepresentation="id"
          icon={DriversIcon}
        />
        <Resource
          name="Rides"
          options={{ label: 'Rides' }}
          list={RidesList}
          create={RidesCreate}
          edit={RidesEdit}
          recordRepresentation="origin"
          icon={RidesIcon}
        />
        <Resource
          name="Vehicles"
          options={{ label: 'Vehicles' }}
          list={VehiclesList}
          create={VehiclesCreate}
          edit={VehiclesEdit}
          recordRepresentation="id"
          icon={VehiclesIcon}
        />
        <Resource
          name="Payments"
          options={{ label: 'Payments' }}
          list={PaymentsList}
          create={PaymentsCreate}
          edit={PaymentsEdit}
          recordRepresentation="paymentMethods"
          icon={PaymentsIcon}
        />
        <CustomRoutes noLayout>
          {/*This renders the login UI on the /auth route*/}
          {getSuperTokensRoutesForReactRouterDom(reactRouterDom)}
          {/*Your app routes*/}
        </CustomRoutes>
      </Admin>
    </BrowserRouter>
  </SuperTokensWrapper>
);

export default App;
