//Source code generated by AppGPT (www.appgpt.tech)
import { Card, CardContent, CardHeader } from '@mui/material';
export const Dashboard = () => (
  <Card>
    <CardHeader title="Share Car Trip" />
    <CardContent>
      Taxi booking services and also sharing rides allow you to hail a taxi
      through a mobile app or website. This can be a convenient option if you
      need a ride immediately or don't feel comfortable carpooling with
      strangers.
      <p>
        Built with{' '}
        <a
          href="https://www.appgpt.tech"
          target="_blank"
          rel="noopener noreferrer"
        >
          AppGPT
        </a>
      </p>
    </CardContent>
  </Card>
);
